// <auto-generated />
namespace Chat_Server.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addblockingtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addblockingtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202305091613192_Add-blocking-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
